config/routes.rb
Audit::Application.routes.draw do

  devise_for :users
  resources :mytasks
  resources :calendars
  resources :dashboards
  resources :auditinits
  resources :catvalues
  resources :categories
  resources :configures
  resources :accounts, :only => [:index, :new, :create, :destroy]

  resources :questions 

  resources :auditinits do 
    resources :questions 
  end

  match '/cososcale' => 'configures#cososcale' , :as => '/cososcale'

  post '/calendars/setmode', to: 'calendars#setmode', as: 'setmode'

  root :to => 'dashboards#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :question, :auditinit_id

  belongs_to :auditinit
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
    @audits = Auditinit.all
  end

  def new
    @question = Question.new(:auditinit_id => params[:auditinit_id])
  end

  def show
    @question = Question.find(params[:id])
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(params[:question])
    if @question.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(params[:question],:auditinit_id => params[:auditinit_id])
      redirect_to root_path
    else
      render action: "edit"
    end
  end

  def destory
    @question = Question.find(params[:id])
    @question.destory
    redirect_to root_path
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
	
	<% if @question.errors.any? %>
          <div class="container" id="error_explanation">
            <div class="row-fluid">
              <div class="col-lg-5 col-lg-offset-3">
                <div class="well well-sm">
                  <h2><%= pluralize(@question.errors.count, "error") %> prohibited this businessunit from being saved:</h2>
                    <ul>  
                      <% @question.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                      <% end %>
                    </ul>
                </div>
              </div>
            </div>
          </div>
        <% end %>
    <%= f.hidden_field :auditinit_id, :value => params[:auditinit_id] %>
    <%= f.text_area :question, :rows => 5, :cols => 25 , :placeholder => 'Enter your question' %>
    <%= f.submit 'Add Question' %>

<% end %>

app/views/questions/edit.html.erb
<h1>Questions#edit</h1>
<p>Find me in app/views/questions/edit.html.erb</p>

app/views/questions/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Preaudit</title>
</head>
<body>

	<!-- Rendering menu  -->
	<%= render :partial => "layouts/menu" %>

	<!-- Main Content -->
	


	<div class="container" , style="height:900px" >	

		<% @audits.each do |a| %>
		<div class="panel panel-primary">

			<div class="panel-heading">
				<%= a.title %>
			</div>

			<div class="panel-body">
				Type : <%= a.a_type %>
				<br />
				Start Date : <%= a.start_date %>
				<br />
				End Date : <%= a.end_date %>
				<br />
				<br />
				<%= link_to " Add Finding", new_auditinit_question_path(a.id), class: "btn btn-default btn-sm pull-right" %> 
			</div>
		</div>
		<% end %>
	</div>


</body>
</html>

app/views/questions/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Edit Your Audit</title>
</head>
<body>

<!-- Rendering Menu -->
	<%= render :partial => 'layouts/menu' %>

<!-- Renderinf Form -->
	<%= render "form" %>

</body>
</html>

app/views/questions/show.html.erb
<h1>Questions#show</h1>
<p>Find me in app/views/questions/show.html.erb</p>