config/routes.rb
Audit::Application.routes.draw do

  devise_for :users
  resources :mytasks
  resources :calendars
  resources :dashboards
  resources :auditinits
  resources :catvalues
  resources :categories
  resources :configures
  resources :accounts, :only => [:index, :new, :create, :destroy]

  resources :questions 

  resources :auditinits do 
    resources :questions 
  end

  match '/cososcale' => 'configures#cososcale' , :as => '/cososcale'

  post '/calendars/setmode', to: 'calendars#setmode', as: 'setmode'

  root :to => 'dashboards#index'

end

app/models/auditinit.rb
class Auditinit < ActiveRecord::Base
  attr_accessible :title,:purpose,:scope,:summary,:start_date,:end_date,:close_date,:target_date,:a_type,:department,:location,:auditor_name,:auditor_email,:auditee_name,:auditee_email,:user_id , :client_name , :c_type


  # Relationship with User 
   belongs_to :user
   belongs_to :account

  # Relationship with Categories and Values
 belongs_to :catvalues


 # Relationship with Questions
 has_many :questions

has_paper_trail

  # Validation
  validates :auditee_email, :auditee_name, :auditor_email , :auditor_name, :title , :presence => true

  # Self Audit
  validate :cannot_audit_self
  def cannot_audit_self
    self.errors[:base] << "You can not audit yourself." if self.auditee_email == self.auditor_email
  end



end

app/controllers/auditinits_controller.rb
class AuditinitsController < ApplicationController

	def index
		@auditinits = current_user.auditinits.all
	end

	def show
		 @auditinit = current_user.auditinits.find(params[:id])
	end

	def new
		@auditinit = current_user.auditinits.new
		@atype = Catvalue.find(:all ,:conditions => ['categories_id = 4'])
		@location = Catvalue.find(:all,:conditions => ['categories_id = 2'])
		@department = Catvalue.find(:all,:conditions => ['categories_id= 1'])
		@team = Catvalue.find(:all,:conditions=> ['categories_id = 3'])
		@compliance = Catvalue.find(:all,:conditions => ['categories_id = 5'])
		@auditor = Account.find(:all)
	end

	def edit
		@auditinit = current_user.auditinits.find(params[:id])
		@atype = Catvalue.find(:all)
		@location = Catvalue.find(:all,:conditions => ['categories_id = 2'])
		@department = Catvalue.find(:all,:conditions => ['categories_id= 1'])
		@team = Catvalue.find(:all,:conditions=> ['categories_id = 3'])
		@compliance = Catvalue.find(:all,:conditions => ['categories_id = 5'])
		@auditor = Account.find(:all)
	end

	def create
		@auditinit = current_user.auditinits.new(params[:auditinit])
		
		if @auditinit.save
        	redirect_to root_path, notice: 'auditinit was successfully created.'
        else
        	render action: "new"
        end
     
    end

	def update
		
		@auditinit = current_user.auditinits.find(params[:id])

		if @auditinit.update_attributes(params[:auditinit])
			redirect_to auditinits_path, notice: 'Audit was successfully updated'
		else
			render action: "edit"		
		end
		
	end

	def destroy
		@auditinit = current_user.auditinits.find(params[:id])
		@auditinit.destroy
		redirect_to auditinits_url
	end
end

app/helpers/auditinits_helper.rb
module AuditinitsHelper
end

app/views/auditinits/_audit_step.html.erb
<div class="tab-pane active" id="organization">
              <br />
              <p class="mypara">Step 1 0f 4</p>
<div class="form-inputs">
      				  <div class="input-sm">
        				  <div class="col-lg-7">
			     		    	<%= f.label "Audit Title" %>
			       				<%= f.text_field :title, :class =>  "form-control" %>
			  	    	  </div>
			        	</div>
    				    <br/><br/>
    				    <div class="input-sm">
        			    <div class="col-lg-7">
    						    <%= f.label "Audit Purpose" %>
							      <%= f.text_area :purpose , :rows => 2, :cols => 15 , :class =>  "form-control" %>
   			    		  </div>
    				  	</div>
    				  	<br/><br/>
    				  	<div class="input-sm">
         					<div class="col-lg-7">
      							<%= f.label "Audit Scope" %>
						    		<%= f.text_area :scope , :rows => 2, :cols => 25 ,    :class =>  "form-control" %>
      						</div>
      					</div>
      					<br/><br/>
      					<div class="input-sm">
          				<div class="col-lg-7">
      							<%= f.label "Audit Summary" %>
						    		<%= f.text_area :summary , :rows => 2, :cols => 25 ,    :class =>  "form-control"%>
						      </div>
      					</div>
       					<br/><br/>                   
    			    </div>
              </div>

app/views/auditinits/_confirmation_step.html.erb
            <div class="tab-pane" id="confirmation">
              <br />
              <p class="mypara">Step 4 0f 4</p>

<%=h @auditinit.title %>

                <div class="form-inputs">
                  <div class="input-sm">
                    <div class="col-lg-10">
                      <%= f.submit 'Submit',  :class => "btn btn-success btn-sm" %>
                    </div>
                  </div>
                  <br/><br/>      
                </div>
                </div>

app/views/auditinits/_form.html.erb
<script type="text/javascript">

// date picker
  $(function() {
     $( "#datepicker" ).datepicker({
      dateFormat: "dd-mm-yy"    });
     $( "#datepicker1" ).datepicker({
      dateFormat: "dd-mm-yy"    });     
  });

</script>

<%= form_for(@auditinit) do |f| %>

<div class="panel panel-primary">
  <div class="panel-heading">Create New Audit</div>
    <div class="panel-body" style="height:900px">
      <div class="col-xs-12 col-sm-6 col-md-8 col-lg-offset-1">

      <!-- Error Message -->

        <% if @auditinit.errors.any? %>
          <div class="container" id="error_explanation">
            <div class="row-fluid">
              <div class="col-lg-5 col-lg-offset-3">
                <div class="well well-sm">
                  <h2><%= pluralize(@auditinit.errors.count, "error") %> prohibited this businessunit from being saved:</h2>
                    <ul>  
                      <% @auditinit.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                      <% end %>
                    </ul>
                </div>
              </div>
            </div>
          </div>
        <% end %>

      <div class="container offset well">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#organization" data-toggle="tab">Audit</a></li>
          <li><a href="#client" data-toggle="tab">Plan</a></li>
          <li><a href="#team" data-toggle="tab">Team </a></li>
          <li><a href="#confirmation" data-toggle="tab">Confirmation</a></li>
        </ul>
            
      <div class="tab-content">
        <div class="tab-pane active" id="organization">
        <br />
          <p class="mypara">Step 1 0f 4</p>
            <div class="form-inputs">
              <div class="input-sm">
                  <div class="col-lg-10">
                <%= f.label "Audit Title" %>
              <%= f.text_field :title, :class =>  "form-control" %>
                </div>
                </div>
               <br/><br/>
               <div class="input-sm">
                   <div class="col-lg-10">
                   <%= f.label "Audit Purpose" %>
                 <%= f.text_area :purpose , :rows => 5, :cols => 25 , :class =>  "form-control" %>
                    </div>
              </div>
              <br/><br/>
              <div class="input-sm">
                  <div class="col-lg-10">
                    <%= f.label "Audit Scope" %>
                <%= f.text_area :scope , :rows => 5, :cols => 25 ,    :class =>  "form-control" %>
                  </div>
                </div>
                <br/><br/>
                <div class="input-sm">
                    <div class="col-lg-10">
                    <%= f.label "Audit Summary" %>
                <%= f.text_area :summary , :rows => 5, :cols => 25 ,    :class =>  "form-control"%>
                </div>
                </div>
                <br/><br/>                   
            </div>

  
        </div>

        <div class="tab-pane" id="client">
        <br />
        <p class="mypara">Step 2 0f 4</p>
            <div class="form-inputs">
            <div class="input-sm">
                  <div class="col-lg-10">
                <%= f.label "Client Name" %>
              <%= f.text_field :client_name  ,:class =>  "form-control input-sm" %>
                </div>
                </div>
               <br/><br/>
              <div class="input-sm">
                  <div class="col-lg-10">
                <%= f.label "Type" %>
              <%= f.collection_select :a_type, @atype, :v_name ,:v_name %>
                </div>
                </div>
               <br/><br/>
               <div class="input-sm">
                  <div class="col-lg-10">
                <%= f.label "Type" %>
              <%= f.collection_select :c_type, @compliance, :v_name ,:v_name %>
                </div>
                </div>
               <br/><br/>
               <div class="input-sm">
                  <div class="col-lg-10">
                    <%= f.label "Department" %>
                    <%= f.collection_select :department , @department, :v_name ,:v_name %> 
                  </div>
              </div>
              <br/><br/>
              <div class="input-sm">
                  <div class="col-lg-10">
                    <%= f.label "Location" %>
                    <%= f.collection_select :location , @location, :v_name ,:v_name %> 
                  </div>
              </div>
              <br/><br/>
              <div class="input-sm">
                  <div class="col-lg-4">
                 <%= f.label "Start Date" %>
                 <%= f.datepicker :start_date, :id => :datepicker ,:class =>  "form-control input-sm" %>
                  </div>
                </div>
                <br/><br/>
                <div class="input-sm">
                    <div class="col-lg-4">            
                <%= f.label "End Date " %>
                <%= f.datepicker :end_date, :id => :datepicker1, :class =>  "form-control input-sm" %>  
                </div>
                </div>
                <br/><br/>                   
            </div>
        </div>

        <div class="tab-pane" id="team">
        <br />
        <p class="mypara">Step 3 0f 4</p>
            <div class="form-inputs">
              <div class="input-sm">
                  <div class="col-lg-10">
                <%= f.label "Auditor Name" %>
              <%= f.text_field :auditor_name   ,:class =>  "form-control"%>
                </div>
                </div>
               <br/><br/>
               <div class="input-sm">
                   <div class="col-lg-10">
              <%= f.label "Auditor Email" %>
              <%= f.text_field :auditor_email  ,:class =>  "form-control"%>
                    </div>
              </div>
              <br/><br/>
              <div class="input-sm">
                  <div class="col-lg-10">
                 <%= f.label "Auditee Name" %>
                 <%= f.text_field :auditee_name ,:class =>  "form-control" %>
                  </div>
                </div>
                <br/><br/>
                <div class="input-sm">
                    <div class="col-lg-10">           
                <%= f.label "Auditee Email" %>
                <%= f.text_field :auditee_email ,:class =>  "form-control" %>
                </div>
                </div>
                <br/><br/>                   
            </div>
        </div>

        <div class="tab-pane" id="confirmation">
        <br />
        <p class="mypara">Step 4 0f 4</p>
            <div class="form-inputs">
              <div class="input-sm">
                <div class="col-lg-10">
                <%= f.submit 'Submit',  :class => "btn btn-success btn-sm" %>
                </div>
              </div>
               <br/><br/>      
            </div>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/auditinits/_plan_step.html.erb
            <div class="tab-pane" id="client">
              <br />
              <p class="mypara">Step 2 0f 4</p>

<div class="form-inputs">
                <div class="input-sm">
                  <div class="col-lg-10">
                    <%= f.label "Client" %>
                    <%= f.text_field :client_name  ,:class =>  "form-control input-sm" %>
                  </div>
                </div>
                <br/><br/>
    		  		  <div class="input-sm">
          			  <div class="col-lg-10">
					        	<%= f.label "Type" %>
                    <%= f.collection_select :a_type , @atype, :v_name ,:v_name , {}, {:class =>  "drop-down"} %>
				    	    </div>
			          </div>
                 <br/><br/>
                <div class="input-sm">
                  <div class="col-lg-10">
                    <%= f.label "Department" %>
                    <%= f.collection_select :department , @department, :v_name ,:v_name , {}, {:class =>  "drop-down"} %>
                  </div>
                </div>
                 <br/><br/>
                <div class="input-sm">
                  <div class="col-lg-10">
                    <%= f.label "Compliance" %>
                    <%= f.collection_select :c_type , @compliance, :v_name ,:v_name , {}, {:class =>  "drop-down"} %>
                  </div>
                </div>
    				    <br/><br/>
    				    <div class="input-sm">
        			    <div class="col-lg-10">
    					     	<%= f.label "Location" %> 
                    <%= f.collection_select :location , @location, :v_name ,:v_name , {}, {:class =>  "drop-down"}  %>
   			    		  </div>
    				  	</div>
    					  <br/><br/>
    					  <div class="input-sm">
         					<div class="col-lg-3">
							      <%= f.label "Start Date" %>
							      <%= f.datepicker :start_date, :id => :datepicker ,:class =>  "form-control input-sm" %>
      						</div>
      				  </div>
      				  <br/><br/>
      				  <div class="input-sm">
          			  <div class="col-lg-3">						
							   	  <%= f.label "End Date " %>
								    <%= f.datepicker :end_date, :id => :datepicker1, :class =>  "form-control input-sm" %>	
						      </div>
      				  </div>
       				  <br/><br/>                   
    				  </div>
              </div>

app/views/auditinits/_team_step.html.erb
            <div class="tab-pane" id="team">
              <br />
              <p class="mypara">Step 3 0f 4</p>
<div class="form-inputs">
    		  		  <div class="input-sm">
          				<div class="col-lg-10">
				  	    	  <%= f.label "Auditor Name" %>
                    <%= f.collection_select :auditor_name  , @auditor, :name ,:name , {}, {:class =>  "drop-down"} %>

				      	  </div>
			          </div>
    				  	<br/><br/>
    				  	<div class="input-sm">
         					<div class="col-lg-10">
							      <%= f.label "Auditee Name" %>
                    <%= f.collection_select :auditee_name  , @auditor, :name ,:name , {}, {:class =>  "drop-down"} %>
      						</div>
      			  	</div>
      			  	<br/><br/>                 
    			  	</div>
              </div>

app/views/auditinits/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Edit Your Audit</title>
</head>
<body>

<!-- Rendering Menu -->
	<%= render :partial => 'layouts/menu' %>

<!-- Renderinf Form -->
	<%= render "form" %>

</body>
</html>

app/views/auditinits/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Audit</title>
</head>
<body>


	<!-- Rendering menu  -->
	<%= render :partial => "layouts/menu" %>

	<!-- Main -->

	<h1 class="myfont">Audit Initation</h1>
	<div class="container" , style="height:900px" >	

		<div class="btn btn-default btn-sm pull-right">
			<span class="glyphicon glyphicon-plus"></span>
			<%= link_to 'New' , new_auditinit_path %>
		</div>

		<br /> 
		<br />

		<% @auditinits.each do |auditinit| %>
		<div class="panel panel-primary">

			<div class="panel-heading">
				<%= auditinit.title %>
			</div>

			<div class="panel-body">
				Type : <%= auditinit.a_type %>
				<br />
				Start Date : <%= auditinit.start_date %>
				<br />
				End Date : <%= auditinit.end_date %>
				<br />
				<br />
				<%= link_to 'Manage Audit', edit_auditinit_path(auditinit), :class =>"btn btn-default btn-sm pull-right"  %>
				<%= link_to 'Review', auditinit  ,:class =>  "btn btn-default btn-sm pull-right"%>
				<%= link_to 'Delete', auditinit, method: :delete, data: { confirm: 'Are you sure?' }, :class =>  "btn btn-default btn-sm pull-right" %>
				
			</div>
		</div>
		<% end %>
	</div>

</body>
</html>

app/views/auditinits/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Edit Your Audit</title>
</head>
<body>

<!-- Rendering Menu -->
	<%= render :partial => 'layouts/menu' %>

<!-- Renderinf Form -->
	<%= render "form" %>

</body>
</html>

app/views/auditinits/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Review Audit</title>
</head>
<body>

	<!-- Rendering menu  -->
	<%= render :partial => "layouts/menu" %>


	<!-- Main Layout -->

	<div class="container">

		<div class="panel panel-primary">

			<div class="panel-heading">
				<%= @auditinit.title %>
			</div>
			
			<div>
			<div class="panel-body">
				<div>
					<label>Purpose</label>
					<br />
					<%= @auditinit.purpose %>
				</div>
				<br />
				<div>
					<label>Scope</label>
					<br />
					<%= @auditinit.scope %>
				</div>
				<br />
				<div>
					<label>Summary</label>
					<br />
					<%= @auditinit.summary %>
				</div>

				<hr>

				<div>
					<label>Client</label>
					<br />
					<%= @auditinit.client_name %>
				</div>
				<br />
				<div>
					<label>Location</label>
					<br />
					<%= @auditinit.location %>
				</div>
				<br />
				<div>
					<label>Start Date</label>
					<br />
					<%= @auditinit.start_date %>
				</div>
				<br />
				<div>
					<label>End Date</label>
					<br />
					<%= @auditinit.end_date %>
				</div>

				<hr>

				<div>
					<label>Auditor Details</label>
					<br />
					<%= @auditinit.auditor_name%>
					<%= @auditinit.auditor_email %>
				</div>
				<br />

				<div>
					<label>Auditee Details</label>
					<br />
					<%= @auditinit.auditee_name %>
					<%= @auditinit.auditee_email %>
				</div>
				<br />

				<hr>

				<%= link_to 'Edit', edit_auditinit_path(@auditinit) , :class => "btn btn-primary" %> 
				<%= link_to 'Back', auditinits_path , :class => "btn btn-primary" %>

			</div>
			
		</div>
		
	</div>
	
</body>
</html>

    