config/routes.rb
Audit::Application.routes.draw do

  devise_for :users
  resources :mytasks
  resources :calendars
  resources :dashboards
  resources :auditinits
  resources :catvalues
  resources :categories
  resources :configures
  resources :accounts, :only => [:index, :new, :create, :destroy]

  resources :questions 

  resources :auditinits do 
    resources :questions 
  end

  match '/cososcale' => 'configures#cososcale' , :as => '/cososcale'

  post '/calendars/setmode', to: 'calendars#setmode', as: 'setmode'

  root :to => 'dashboards#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  
  # create asscociation between user and account table
  has_many :users, :inverse_of => :account, :dependent => :destroy

  accepts_nested_attributes_for :users

  attr_accessible :name, :users_attributes

  has_many :audit_inits

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # GET /accounts
  # GET /accounts.json
  def index
    # @accounts = Account.all
    @account = Account.new
    @account.users.build
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.all
    # @account.users.build
    
    
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(params[:account])
    

       if @account.save
        redirect_to accounts_path
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  # def update
  #   @account = Account.find(params[:id])
def update
  @account = Account.find(params[:id])

   respond_to do |format|
    if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
         format.json { head :no_content }
       else
        format.html { render action: "edit" }
         format.json { render json: @account.errors, status: :unprocessable_entity }
       end
     end
   end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>
<!-- <h1>Listing accounts</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><%= account.name %></td>
    <td><%= link_to 'Show', account %></td>
    <td><%= link_to 'Edit', edit_account_path(account) %></td>
    <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Account', new_account_path %>
 -->

app/views/accounts/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Add New User</title>
  <style type="text/css">
    .form-group.last { margin-bottom:0px; }
  </style>
</head>
<body>


<!-- Rendering menu  -->
  <%= render :partial => "layouts/menu" %>


  <!-- Main -->


  <%= form_for(@account) do |f| %>
   
    
      <div class="panel panel-primary">

        <div class="panel-heading">Settings</div>
        <div class="container offset well">
          <div class="panel-body" style="height:900px">
            <h3 class="mypara">User Management</h3> 
              <div class="form-inputs">
                <div class="input-sm">
                  <div class="col-lg-5">
                    <%= f.label :name %><br />
                    <%= f.text_field :name  , :class =>  "form-control"%>
                  </div>
                </div>
                <br/><br/><br/>
                <%= f.fields_for :users do |user_form| %>
                  <div class="input-sm">
                    <div class="col-lg-5">
                      <%= user_form.label :email %><br />
                      <%= user_form.email_field :email , :class =>  "form-control" %>              
                    </div>
                  </div>
                  <br/><br/><br/>
                  <div class="input-sm">
                    <div class="col-lg-5">
                      <%= user_form.label :password %><br />
                      <%= user_form.password_field :password , :class =>  "form-control" %>
                    </div>
                  </div>  
                  <br/><br/><br/>
                  <div class="input-sm">
                    <div class="col-lg-5">
                      <%= user_form.label :password_confirmation %><br />
                      <%= user_form.password_field :password_confirmation , :class =>  "form-control" %>
                    </div>
                  </div>
                <% end %>
                <br/><br/><br/>
                <div class="input-sm">
                  <div class="col-lg-5">
                  <%= f.submit "Create account" ,  :class => "btn btn-success btn-sm" %>
                  </div>
                </div>
              </div>
          </div>
        </div>
      </div>
  <% end %>
</body>
</html>

app/views/accounts/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Add New User</title>
  <style type="text/css">
    .form-group.last { margin-bottom:0px; }
  </style>
</head>
<body>




  <!-- Main -->


  <%= form_for(@account) do |f| %>
   
    
      <div class="panel panel-primary">

        <div class="panel-heading">Settings</div>
        <div class="container offset well">
          <div class="panel-body" style="height:900px">
            <h3 class="mypara">User Management</h3> 
              <div class="form-inputs">
                <div class="input-sm">
                  <div class="col-lg-10">
                    <%= f.label :name %><br />
                    <%= f.text_field :name %>
                  </div>
                </div>
                <br/><br/><br/>
                <%= f.fields_for :users do |user_form| %>
                  <div class="input-sm">
                    <div class="col-lg-10">
                      <%= user_form.label :email %><br />
                      <%= user_form.email_field :email %>              
                    </div>
                  </div>
                  <br/><br/><br/>
                  <div class="input-sm">
                    <div class="col-lg-10">
                      <%= user_form.label :password %><br />
                      <%= user_form.password_field :password %>
                    </div>
                  </div>  
                  <br/><br/><br/>
                  <div class="input-sm">
                    <div class="col-lg-10">
                      <%= user_form.label :password_confirmation %><br />
                      <%= user_form.password_field :password_confirmation %>
                    </div>
                  </div>
                <% end %>
                <br/><br/><br/>
                <div class="input-sm">
                  <div class="col-lg-10">
                  <%= f.submit "Create account" %>
                  </div>
                </div>
              </div>
          </div>
        </div>
      </div>
  <% end %>
</body>
</html>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @account.name %>
</p>


<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>